repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        stages: [commit]
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        stages: [commit]
        verbose: true
