vars:
  - ndigits: 3

stages:
  split:
    cmd: >-
      python src/split_data.py
      data/origin/data.csv
      data/splitted/train.csv
      data/splitted/test.csv
      ${split}
    deps:
      - data/origin/data.csv
      - src
    outs:
      - data/splitted/train.csv
      - data/splitted/test.csv

  train:
    cmd: >-
      python src/train_model.py
      models/model.pkl
      data/splitted/train.csv
      models/model.pkl
    deps:
      - data/splitted/train.csv
      - src
    outs:
      - models/model.pkl

  test:
    cmd: >-
      python src/test_model.py
      data/splitted/test.csv
      models/model.pkl
      data/predicted/test.csv
      metrics.yaml
      --ndigits ${ndigits}
    deps:
      - models/model.pkl
      - data/splitted/test.csv
      - src
    outs:
      - data/predicted/test.csv
    metrics:
      - metrics.yaml:
          cache: false

plots:
  - train_test_split:
      title: Train test split
      template: templates/train_test_split.json
      x:
        data/splitted/train.csv: target
        data/splitted/test.csv: target
      y:
        data/splitted/train.csv: target
        data/splitted/test.csv: target

  - confusion:
      title: Confusion matrix
      template: confusion
      x:
        data/predicted/test.csv: "true"
      y:
        data/predicted/test.csv: "pred"

  - confidence_score:
      title: Confidence scores
      template: templates/confidence_score.json
      y:
        data/predicted/test.csv: "prob"
